name: remidio_fop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_auth_dart: ^1.0.1
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.13.5

flutter:
  uses-material-design: true
  assets:
    - assets/png/